::ALLOW %CD% TO CHANGE DURING RUNTIME
SETLOCAL ENABLEDELAYEDEXPANSION

::SET CURRENT DIRECTORY AS PROJECT DIRECTORY AND SWITCH TO IT
SET PROJECT_DIR=%1

::SWITCH TO PROJECT DIRECTORY
PUSHD %PROJECT_DIR%

::GO UP UP TO 25 DIRECTORIES AND LOOK FOR header OR makefile
FOR /L %%G IN (1,1,25) DO (
    IF EXIST header SET res=1
    IF EXIST makefile SET res=1

    IF DEFINED res (
        GOTO :EOF
    ) ELSE (
        PUSHD ..
        SET PROJECT_DIR=!CD!
    )
)