::SET ECHO OFF
@echo off

ECHO CONVERTING IMAGES...

::SCRIPT INITIALIZATION
CALL "%~dp0\init.bat"

::FIND PROJECT DIRECTORY
CALL "%VBDE%\system\batch\find-project-dir.bat" %1

::PREPARE ENV VARS
SET VBDE_UNIX=%VBDE:\=/%
SET VBDE_UNIX=%VBDE_UNIX:c:=/c%
SET PROJECT_DIR_UNIX=%PROJECT_DIR:\=/%
SET PROJECT_DIR_UNIX=%PROJECT_DIR_UNIX:c:=/c%

::SWITCH TO PROJECT DIRECTORY
PUSHD "%PROJECT_DIR%"

::COMPILE GRAPHICS WITH GRIT
CALL "%VBDE%\system\batch\launch-grit.bat"
