::SET ECHO OFF
@echo off

::SET TEMPORARY ENVIRONMENT VARIABLES
SET VBDE=C:\vbde

::SET TEMPORARY CYGWIN ENVIRONMENT VARIABLES
SET CYGWIN=nodosfilewarning
SET CHERE_INVOKING=1

::GENERATE SSH KEYS IF NOT EXISTING YET
%VBDE%\cygwin\bin\bash -l -c "[ -f ~/.ssh/id_rsa ] || (echo 'SINCE THIS IS THE FIRST TIME YOU TRY TO ACCESS GIT FROM THIS ACCOUNT, YOU NEED TO CREATE A SSH KEY PAIR.' && ssh-keygen)"

::SWITCH TO ROOT DIRECTORY
PUSHD %VBDE%

::PULL
%VBDE%\cygwin\bin\bash -l -c "git pull"
pause > nul